INSERT INTO Role (name) VALUES ('teller'),('user'),('supervisor');
INSERT INTO Language (language) VALUES ('English'),('French'),('German'),('Italian'),('Portuguese'),('Spanish');
INSERT INTO User (name,company,jobTitle,email,idRole,experience,username,password,enabled,imgUrl) VALUES ('Alejandro Luebs','Globant','Java Developer','alejandro.luebs@globant.com',3,'none','alejandro.luebs','1234',true, 'http://avatars.chesscomfiles.com/images_users/avatars/aluebs_l.gif')
INSERT INTO User (name,company,jobTitle,email,idRole,experience,username,password,enabled,imgUrl) VALUES ('Eugenio Valeiras','Globant','Java Developer','eugenio.valeiras@globant.com',3,'none','eugenio.valeiras','1234',true, 'https://fbcdn-sphotos-a.akamaihd.net/hphotos-ak-ash3/182632_1858255101262_3935695_n.jpg')
INSERT INTO User (name,company,jobTitle,email,idRole,experience,username,password,enabled,imgUrl) VALUES ('Joan Almeida','Globant','Java Developer','joan.almeida@globant.com',3,'none','joan.almeida','1234',true, 'https://fbcdn-sphotos-a.akamaihd.net/hphotos-ak-ash4/378608_2700724688287_699389062_n.jpg')
INSERT INTO User (name,company,jobTitle,email,idRole,experience,username,password,enabled,imgUrl) VALUES ('Sebastian Balay','Globant','Java Developer','sebastian.balay@globant.com',3,'none','sebastian.balay','1234',true, 'https://fbcdn-sphotos-a.akamaihd.net/hphotos-ak-ash3/5376_1206571407064_8322262_n.jpg')
INSERT INTO User (name,company,jobTitle,email,idRole,experience,username,password,enabled,imgUrl) VALUES ('Nicolas Morales','Globant','Java Developer','nicolas.morales@globant.com',2,'none','nicolas.morales','1234',true, 'http://beta.gamevue.net/images/default_profile.jpg')
INSERT INTO User (name,company,jobTitle,email,idRole,experience,username,password,enabled,imgUrl) VALUES ('Daniel Pilla','Globant','Java Developer','daniel.pilla@globant.com',2,'none','daniel.pilla','1234',true, 'http://beta.gamevue.net/images/default_profile.jpg')
INSERT INTO User (name,company,jobTitle,email,idRole,experience,username,password,enabled,imgUrl) VALUES ('Yair Abraham','Globant','Java Developer','yair.abraham@globant.com',2,'none','yair.abraham','1234',true, 'http://beta.gamevue.net/images/default_profile.jpg')
INSERT INTO User (name,company,jobTitle,email,idRole,experience,username,password,enabled,imgUrl) VALUES ('Leandro Mora','Globant','Java Developer','leandro.mora@globant.com',2,'none','leandro.mora','1234',true, 'http://beta.gamevue.net/images/default_profile.jpg')
INSERT INTO User (name,company,jobTitle,email,idRole,experience,username,password,enabled,imgUrl) VALUES ('Mateo Harfuch','Globant','Java Developer','mateo.harfuch@globant.com',2,'none','mateo.harfuch','1234',true, 'http://beta.gamevue.net/images/default_profile.jpg')
INSERT INTO User (name,company,jobTitle,email,idRole,experience,username,password,enabled,imgUrl) VALUES ('Esteban Butti','Globant','Java Developer','esteban.butti@globant.com',2,'none','esteban.butti','1234',true, 'http://beta.gamevue.net/images/default_profile.jpg')
INSERT INTO User (name,company,jobTitle,email,idRole,experience,username,password,enabled,imgUrl) VALUES ('Dawoon Choi','Globant','Java Developer','dawoon.choi@globant.com',2,'none','dawoon.choi','1234',true, 'http://beta.gamevue.net/images/default_profile.jpg')
INSERT INTO User (name,company,jobTitle,email,idRole,experience,username,password,enabled,imgUrl) VALUES ('Facundo Jauregui','Globant','Java Developer','facundo.jauregui@globant.com',2,'none','facundo.jauregui','1234',true, 'http://beta.gamevue.net/images/default_profile.jpg')
INSERT INTO User (name,company,jobTitle,email,idRole,experience,username,password,enabled,imgUrl) VALUES ('Melina Salomon','Globant','Java Developer','melina.salomon@globant.com',2,'none','melina.salomon','1234',true, 'http://beta.gamevue.net/images/default_profile.jpg')
INSERT INTO User (name,company,jobTitle,email,idRole,experience,username,password,enabled,imgUrl) VALUES ('Maria Colombo','Globant','Java Developer','maria.colombo@globant.com',2,'none','maria.colombo','1234',true, 'http://beta.gamevue.net/images/default_profile.jpg');